### ISSUE TITLE
npm 安装报错

### ISSUE THREAD

**Issue by CasbaL** [hantsy/nestjs-sample#317]
**Development Environment:**
 - OS: macOS 10.15.7
 - NodeJS version: v14.15.2
 - Package manager tools: npm

**Describe the bug**
npm install error  

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/mongoose@5.10.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'nestjs-sample'
npm ERR! notarget 
```

**To Reproduce**
npm install

**Additional context**

yarn可以安装成功

**Comment by CasbaL** [comment]
![image](https://user-images.githubusercontent.com/26603379/102434337-869d9380-404f-11eb-88ac-1d4ad790e6e6.png)

**Comment by CasbaL** [comment]
额。yarn 安装的版本不对；
![image](https://user-images.githubusercontent.com/26603379/102435044-ea748c00-4050-11eb-8891-ef98339c2ee0.png)
还是跑不起来
![image](https://user-images.githubusercontent.com/26603379/102435139-109a2c00-4051-11eb-8bf8-a2476191ec0a.png)

**Comment by hantsy** [comment]
I have used a CI configuration to ensure the project config working well, till now there is no breaking reporting there.

Please try the following steps.

1. remove node_modules. 
3. make sure you are using the official Npm registries, as I know many NPM mirrors will delay syncing the packages for days.
4. run `npm install` in the project root folder. If you are using  Windows, try to run as Administrator.

if it is still failed, try to remove the **package lock** file which is always synced to the latest versions, and reinstall. Good luck.

**Comment by hantsy** [comment]
See the build log: https://github.com/hantsy/nestjs-sample/actions?query=workflow%3ABuild

**Comment by hantsy** [comment]
@CasbaL any update?

**Comment by CasbaL** [comment]
> @CasbaL any update?

换了官方镜像可以了，是taobao源的问题
